project:
  type: book
  output-dir: "../../docs"

book:
  title: "Captchas"
  author: "Julio Trecenti"
  date: "2022-10-30"
  chapters:
    - index.qmd
    - introducao.qmd
    - metodologia.qmd
    - resultados.qmd
    - conclusoes.qmd
    - bibliografia.qmd
  appendices:
    - pacote.qmd
  downloads: [pdf]
  page-navigation: true

number-depth: 1

bibliography: [book.bib, captcha.bib, references.bib]
csl: /Users/julio/OneDrive/Documentos/jtrecenti/doutorado/inst/book/abnt.csl

google-scholar: true

format:
  html:
    code-fold: true
  pdf:
    keep-tex: true
    template: assets/tex/template.tex

lang: pt

execute:
  echo: false
  warning: false
  freeze: true

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
    out.width: \linewidth
    R.options:
      knitr.graphics.auto_pdf: true
